version: '3.7'

services:
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - 3300:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - primeira-network

  api:
    build:
      context: .
    container_name: api
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - primeira-network

networks:
  primeira-network:
    driver: bridge

volumes:
  db:
